trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:

  - task: CmdLine@2
    inputs:
      script: 'ping 106.54.247.111'
  - task: SSH@0
    inputs:
      sshEndpoint: '腾讯云'
      runOptions: 'inline'
      inline: |
        cd ./dailer/decision-worklog-remind
        echo "start fetching"
        git fetch --all
        pm2 start deploy.yaml
      failOnStdErr: false
      readyTimeout: '200000'
