trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: SSH@0
    inputs:
      sshEndpoint: "腾讯云"
      runOptions: "inline"
      inline: |
        git fetch --all
        cd ./dailer/decision-worklog-remind
        pm2 start deploy.yaml
      readyTimeout: "200000"
