# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: '106.54.247.111'
    sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3rP00BVy+f1VJMm6N4z+usPMNBb5+I16xDflBEtUTZhvX0M9LQmBoRuyQZAACybEMNmAL13m0AbGHlMLi o1SzzRFSFN8Ji5ppL3zpO8hJZHra4nC6c55z4otj/Ug48KO2j6qLAwP5xN4iG4dO2VxHLjOG7CGtcGmLzlpr/1ReeXl3G/LEoBZrHHUcU2XHt0Wer/CYXc3j sQb/lccn8L7gnANlFiVZkYGy52ZNUFaQXYhLa6z+lPaS7HMzyI5NHv0K+m83tLnAgWlUJQUd9lFqrXNVpykSVKDFy0uZ2yBgfcIYhX1ofvjtMKQtqJ3CbfPk 3t+7BojXpKz1doc6O4Zv zsmj1994@gmail.com'
    sshKeySecureFile: 'tencentPrivateKey'

- script: |
    npm install -g pm2
    npm install
    git checkout matster
    pm2 deploy deploy.yaml production
  displayName: 'npm install and build'
